"""Golden query set for RAG recall and hybrid-retrieval audits."""
from __future__ import annotations


GOLDEN_QUERIES: list[tuple[str, str]] = [
    ("资产负债率高不高", "metric_debt_ratio"),
    ("这家公司债务压力大不大", "metric_debt_ratio"),
    ("How high is the debt ratio?", "metric_debt_ratio"),
    ("流动比率怎么样", "metric_current_ratio"),
    ("短期偿债能力好不好", "metric_current_ratio"),
    ("速动比率高不高", "metric_quick_ratio"),
    ("现金流稳不稳", "metric_cash_flow_level"),
    ("公司现金流情况如何", "metric_cash_flow_level"),
    ("How is the cash flow?", "metric_cash_flow_level"),
    ("经营现金流净额多少", "metric_cash_flow_net"),
    ("营收增长怎么样", "metric_revenue_yoy"),
    ("收入同比涨了多少", "metric_revenue_yoy"),
    ("Revenue growth?", "metric_revenue_yoy"),
    ("利润同比增长吗", "metric_profit_yoy"),
    ("利润率怎么样", "metric_profit_margin"),
    ("毛利率高不高", "metric_gross_margin"),
    ("净利率是多少", "metric_net_margin"),
    ("ROE 怎么样", "metric_roe"),
    ("净资产收益率高不高", "metric_roe"),
    ("ROA 怎么样", "metric_roa"),
    ("总资产周转率如何", "metric_asset_turnover"),
    ("应收账款周转快不快", "metric_receivables_turnover"),
    ("存货周转率怎么样", "metric_inventory_turnover"),
    ("发票数量有多少", "metric_invoice_cnt"),
    ("Invoice count", "metric_invoice_cnt"),
    ("月均开票多少", "metric_invoice_monthly_avg"),
    ("每月平均开多少票", "metric_invoice_monthly_avg"),
    ("发票口径收入多少", "metric_invoice_revenue"),
    ("增值税口径营收是多少", "metric_vat_revenue"),
    ("财务口径收入多少", "metric_finance_revenue"),
    ("客户是不是太集中", "metric_customer_concentration"),
    ("客户HHI是多少", "metric_customer_hhi"),
    ("前五客户占比多少", "metric_customer_top5_concentration"),
    ("大客户依赖严重吗", "metric_customer_concentration"),
    ("Customer concentration", "metric_customer_concentration"),
    ("供应商集中度怎么样", "metric_supplier_concentration"),
    ("供应商HHI是多少", "metric_supplier_hhi"),
    ("前五供应商占比多少", "metric_supplier_top5_concentration"),
    ("客户有多少家", "metric_customer_count"),
    ("供应商有多少家", "metric_supplier_count"),
    ("品目是不是太集中", "metric_category_concentration"),
    ("红字发票有多少", "metric_red_invoice_cnt"),
    ("红冲发票多不多", "metric_red_invoice_cnt"),
    ("作废发票有多少", "metric_void_invoice_cnt"),
    ("作废发票比例多少", "metric_void_invoice_ratio"),
    ("单价差异大不大", "metric_unit_price_ratio"),
    ("增值税税负高不高", "metric_vat_burden"),
    ("VAT burden", "metric_vat_burden"),
    ("所得税税负高不高", "metric_income_tax_burden"),
    ("实际所得税率多少", "metric_income_tax_effective_rate"),
    ("纳税准时率多少", "metric_tax_on_time_rate"),
    ("有没有按时缴税", "metric_tax_on_time_rate"),
    ("欠税多不多", "metric_tax_arrears_cnt"),
    ("Tax arrears", "metric_tax_arrears_cnt"),
    ("税务违法次数多少", "metric_tax_violation_cnt"),
    ("滞纳金和罚款多不多", "metric_tax_late_penalty_cnt"),
    ("申报更正过几次", "metric_correction_times"),
    ("社保人数多少", "metric_social_headcount"),
    ("员工人数是多少", "metric_social_headcount"),
    ("工商变更多不多", "metric_change_cnt"),
    ("社保缴了几个月", "metric_social_months"),
    ("社保趋势怎么样", "metric_social_trend"),
    ("收入对不上吗", "metric_revenue_deviation"),
    ("多口径营收差异大不大", "metric_revenue_deviation"),
    ("多口径平均偏差多少", "metric_cross_avg_deviation"),
    ("多口径最大偏差多少", "metric_cross_max_deviation"),
    ("现金流质量怎么样", "metric_ocf_to_revenue"),
    ("异常凭证占比多少", "metric_invalid_invoice_ratio"),
    ("最近违规距今多久", "metric_violation_recency_days"),
    ("综合风险评分多少", "metric_overall_score"),
    ("税务健康得分多少", "metric_tax_health_score"),
    ("经营真实性得分多少", "metric_authenticity_score"),
    ("财务健康得分多少", "metric_finance_score"),
    ("行业地位得分多少", "metric_industry_score"),
    ("法律合规得分多少", "metric_legal_score"),
    ("发票健康得分多少", "metric_invoice_score"),
    ("纳税信用分多少", "metric_credit_score"),
]
